# Generated by Django 3.0.5 on 2020-05-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttask',
            name='add_goods_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttask',
            name='delet_godds_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
